"""add Pot and PlantPot models, remove price/image/size/pot_container from Plant

Revision ID: 032b792f13d9
Revises: bf7470231526
Create Date: 2026-04-10 17:15:57.362785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032b792f13d9'
down_revision = 'bf7470231526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_plant')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
        batch_op.drop_column('size')
        batch_op.drop_column('price')
        batch_op.drop_column('pot_container')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pot_container', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True))

    op.create_table('_alembic_tmp_plant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('common_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('scientific_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('pot_container', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('colour', sa.VARCHAR(length=50), nullable=True),
    sa.Column('growth_width', sa.FLOAT(), nullable=True),
    sa.Column('growth_height', sa.FLOAT(), nullable=True),
    sa.Column('fragrant', sa.BOOLEAN(), nullable=True),
    sa.Column('frost_sensitive', sa.BOOLEAN(), nullable=True),
    sa.Column('flowering_period', sa.VARCHAR(length=200), nullable=True),
    sa.Column('light_requirements', sa.VARCHAR(length=200), nullable=True),
    sa.Column('soil_requirements', sa.VARCHAR(length=200), nullable=True),
    sa.Column('planting_advice', sa.VARCHAR(length=200), nullable=True),
    sa.Column('watering_needs', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pruning_needs', sa.VARCHAR(length=200), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('species_id', sa.INTEGER(), nullable=True),
    sa.Column('variety_id', sa.INTEGER(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_plant_category_id_category')),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_plant_species_id_species')),
    sa.ForeignKeyConstraint(['variety_id'], ['variety.id'], name=op.f('fk_plant_variety_id_variety')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
