"""initial

Revision ID: 0443157c2ac7
Revises: 
Create Date: 2026-03-19 18:52:36.485300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0443157c2ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('pot_container', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('growth_width', sa.Float(), nullable=True),
    sa.Column('growth_height', sa.Float(), nullable=True),
    sa.Column('fragrant', sa.Boolean(), nullable=True),
    sa.Column('frost_sensitive', sa.Boolean(), nullable=True),
    sa.Column('flowering_period', sa.String(length=200), nullable=True),
    sa.Column('light_requirements', sa.String(length=200), nullable=True),
    sa.Column('soil_requirements', sa.String(length=200), nullable=True),
    sa.Column('planting_advice', sa.String(length=200), nullable=True),
    sa.Column('watering_needs', sa.String(length=200), nullable=True),
    sa.Column('pruning_needs', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant')
    # ### end Alembic commands ###
