"""add image_filename to plant and category

Revision ID: 4af8115c82bd
Revises: 8fd52a4dbe83
Create Date: 2026-03-26 22:01:03.750995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af8115c82bd'
down_revision = '8fd52a4dbe83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
