"""add foreign keys to plant model

Revision ID: 8fd52a4dbe83
Revises: 0443157c2ac7
Create Date: 2026-03-20 14:31:20.203466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd52a4dbe83'
down_revision = '0443157c2ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('species_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('variety_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_plant_variety_id_variety'), 'variety', ['variety_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_plant_species_id_species'), 'species', ['species_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_plant_category_id_category'), 'category', ['category_id'], ['id'])
        batch_op.drop_column('variety')
        batch_op.drop_column('category')
        batch_op.drop_column('species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('variety', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_plant_category_id_category'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_plant_species_id_species'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_plant_variety_id_variety'), type_='foreignkey')
        batch_op.drop_column('variety_id')
        batch_op.drop_column('species_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
