"""add images to plant, remove from plant-pot

Revision ID: bc0e01ca8b24
Revises: 032b792f13d9
Create Date: 2026-04-24 19:05:01.958264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0e01ca8b24'
down_revision = '7d96b9a1c5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    with op.batch_alter_table('plant_pot', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
